#!/usr/bin/env python3
"""Emit scripts/sh4_symbols.lua from the project's validated PC addresses.

The Lua runtime auto-loads this file and binds it to ``sh4.sym`` so scripts can
write ``sh4.write_f32(sh4.sym.kRenderFrameSecondsFloat, 1/60)`` instead of pasting
raw addresses. Two validated sources are merged:

  * ``src/sh4/addresses.h`` -- the hand-verified PC addresses the runtime already
    relies on (the project's source of truth). Only ``uintptr_t`` constants whose
    value looks like a code/data address (>= 0x00400000) are exported; small
    offsets, float defaults, etc. are skipped.
  * ``tools/sdk/generated/function_map.json`` -- any PS2<->PC correlation a human
    promoted to ``status: validated`` (its ``validated_pc.pc_addr`` keyed by the
    PS2 symbol). Auto-proposed *candidates* are intentionally NOT exported.

Copy the output next to the game exe as ``scripts/sh4_symbols.lua`` (or point the
runtime's scripts dir at it). Regenerate whenever addresses.h or the validated
correlations change.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ADDRESSES_H = ROOT / "src" / "sh4" / "addresses.h"
FUNCTION_MAP = ROOT / "tools" / "sdk" / "generated" / "function_map.json"
DEFAULT_OUT = ROOT / "tools" / "sdk" / "generated" / "sh4_symbols.lua"

ADDR_DECL = re.compile(r"inline\s+constexpr\s+uintptr_t\s+(\w+)\s*=\s*(0x[0-9A-Fa-f]+)")
MIN_ADDR = 0x00400000  # below the image base it is an offset/enum, not an address


def parse_addresses_h(path: Path) -> dict[str, int]:
    out: dict[str, int] = {}
    if not path.exists():
        return out
    for name, value in ADDR_DECL.findall(path.read_text(encoding="utf-8")):
        addr = int(value, 16)
        if addr >= MIN_ADDR:
            out[name] = addr
    return out


def parse_validated_map(path: Path) -> dict[str, int]:
    out: dict[str, int] = {}
    if not path.exists():
        return out
    data = json.loads(path.read_text(encoding="utf-8"))
    for entry in data.get("functions", []):
        if entry.get("status") != "validated":
            continue
        vp = entry.get("validated_pc") or {}
        addr = vp.get("pc_addr")
        sym = entry.get("ps2_symbol")
        if not sym or addr is None:
            continue
        out[sym] = int(addr, 16) if isinstance(addr, str) else int(addr)
    return out


def emit_lua(symbols: dict[str, int], sources: list[str]) -> str:
    lines = [
        "-- GENERATED by tools/sdk/generate_lua_symbols.py -- do not edit by hand.",
        "-- Validated SH4 PC addresses, bound to sh4.sym by the Lua runtime.",
        f"-- sources: {', '.join(sources)}",
        "return {",
    ]
    for name in sorted(symbols):
        lines.append(f"    {name} = 0x{symbols[name]:08X},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate scripts/sh4_symbols.lua from validated addresses.")
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--addresses", type=Path, default=ADDRESSES_H)
    parser.add_argument("--function-map", type=Path, default=FUNCTION_MAP)
    args = parser.parse_args()

    symbols = parse_addresses_h(args.addresses)
    sources = [str(args.addresses.relative_to(ROOT)) if args.addresses.is_relative_to(ROOT) else str(args.addresses)]

    validated = parse_validated_map(args.function_map)
    if validated:
        symbols.update(validated)
        sources.append(f"{args.function_map.name} (validated)")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(emit_lua(symbols, sources), encoding="utf-8", newline="\n")
    print(f"wrote {args.output}")
    print(f"  symbols: {len(symbols)}  (addresses.h={len(parse_addresses_h(args.addresses))}, validated_map={len(validated)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
